{
 "title": "tides",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "station_name1",
    "query": "show tag values with key = station_name"
   },
   {
    "name": "code1",
    "query": "SHOW TAG VALUES WITH KEY = code  WHERE station_name = '$station_name1'"
   },
   {
    "name": "station_name2",
    "label": "station name 2",
    "query": "show tag values with key = station_name"
   },
   {
    "name": "code2",
    "label": "code",
    "query": "SHOW TAG VALUES WITH KEY = code  WHERE station_name = '$station_name2'"
   },
   {
    "name": "inter",
    "label": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "maps", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Locations of chosen stations",
   "type": "geomap",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 1 },
   "targets": [
    {
     "alias": "$code1",
     "query": "select * from tide_stations where code = '$code1' "
    },
    {
     "alias": "$code2",
     "query": "select * from tide_stations where code = '$code2' "
    }
   ]
  },
  {
   "title": "permament tide station locations",
   "type": "geomap",
   "gridPos": { "h": 11, "w": 11, "x": 11, "y": 1 },
   "targets": [
    { "query": "select * from tide_stations" }
   ]
  },
  { "title": "observed tide levels", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "tide height",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 22, "x": 0, "y": 13 },
   "targets": [
    {
     "alias": "$station_name1",
     "query": "SELECT level  from tide_level  WHERE siteName='$code1'"
    },
    {
     "alias": "$station_name2",
     "query": "SELECT level  from tide_level  WHERE siteName='$code2'"
    }
   ]
  },
  {
   "title": "tide for $station_name1",
   "type": "table",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "SELECT *  from tide_level  WHERE siteName='$code1' and $timeFilter"
    }
   ]
  },
  {
   "title": "tide for $station_name2",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 10, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "SELECT *  from tide_level  WHERE siteName='$code2' and $timeFilter"
    }
   ]
  },
  { "title": "missing data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Missing data for $station_name1 grouped by ($inter)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "alias": "how many ",
     "query": "SELECT count(count_no) FROM \"missing_data\" WHERE siteName='$code1' AND $timeFilter GROUP BY TIME($inter)"
    }
   ]
  },
  {
   "title": "Missing data for $station_name2 grouped by ($inter)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "alias": "how many ",
     "query": "SELECT count(count_no) FROM \"missing_data\" WHERE siteName='$code2' AND $timeFilter GROUP BY TIME($inter)"
    }
   ]
  },
  {
   "title": "Info",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "options": {
    "content": "# informaton\n\nThere are 3600 observations daily.  \n\"No data\" in \"missing data\" charts means - there's no missing data (all observations were stored and are avialalbe)"
   }
  }
 ]
}