{
 "title": "tides",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "station_name1",
    "label": "station 1",
    "query": "show tag values with key = station_name"
   },
   {
    "name": "code1",
    "label": "code",
    "query": "SHOW TAG VALUES WITH KEY = code  WHERE station_name = '$station_name1'"
   },
   {
    "name": "station_name2",
    "label": "station 2",
    "query": "show tag values with key = station_name"
   },
   {
    "name": "code2",
    "label": "code",
    "query": "SHOW TAG VALUES WITH KEY = code  WHERE station_name = '$station_name2'"
   },
   {
    "name": "inter",
    "label": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Information",
   "type": "text",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# This dashoard presents water level measured at permament tide stations in Norway    \ndata sourcee: [www.kartverket.no](https://www.kartverket.no/en/at-sea/se-havniva/tides-and-water-level/permanent-tide-gauges)  \nThe data is collected every hour.   \nMeasurements are done every 10 minutes.    \n24 permanent tide gauges in Norway: 23 are located along the Norwegian coast and one is located in Ny-Ålesund on Svalbard.  \nPlease choose 2 tide stations from menu above to compare. \n\nThe dashboard was done as project for [GEO4300](https://www.uio.no/studier/emner/matnat/geofag/GEO4300/) at Oslo University, 2022   \nProject particpants:   \nErik Marthinsen  and Anna Wojciechowska  \ncontact: anna.wojciechowska@gmail.com"
   }
  },
  { "title": "maps", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Locations of chosen stations",
   "type": "geomap",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 9 },
   "targets": [
    {
     "alias": "$code1",
     "query": "select * from tide_stations where code = '$code1' "
    },
    {
     "alias": "$code2",
     "query": "select * from tide_stations where code = '$code2' "
    }
   ]
  },
  {
   "title": "permament tide station locations",
   "type": "geomap",
   "description": "Location of all Norwegian tide stations",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 9 },
   "targets": [
    { "query": "select * from tide_stations   " }
   ]
  },
  { "title": "observed tide levels", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "tide height",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "alias": "$station_name1",
     "query": "SELECT level  from tide_level  WHERE siteName='$code1'"
    },
    {
     "alias": "$station_name2",
     "query": "SELECT level  from tide_level  WHERE siteName='$code2'"
    }
   ]
  },
  {
   "title": "tide for $station_name1",
   "type": "table",
   "gridPos": { "h": 13, "w": 11, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "SELECT *  from tide_level  WHERE siteName='$code1' and $timeFilter"
    }
   ]
  },
  {
   "title": "tide for $station_name2",
   "type": "table",
   "gridPos": { "h": 13, "w": 13, "x": 11, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "SELECT *  from tide_level  WHERE siteName='$code2' and $timeFilter"
    }
   ]
  },
  { "title": "missing data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Missing data for $station_name1 grouped by ($inter)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "alias": "how many ",
     "query": "SELECT count(count_no) FROM \"missing_data\" WHERE siteName='$code1' AND $timeFilter GROUP BY TIME($inter)"
    }
   ]
  },
  {
   "title": "Missing data for $station_name2 grouped by ($inter)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "alias": "how many ",
     "query": "SELECT count(count_no) FROM \"missing_data\" WHERE siteName='$code2' AND $timeFilter GROUP BY TIME($inter)"
    }
   ]
  },
  {
   "title": "Info",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "options": {
    "content": "# informaton\n\nThere are 144 observations for each station daily.  \n\"No data\" in \"missing data\" charts means - there's no missing data (all observations were stored and are avialalbe)\nKnown missing data:  \n2022:  \nKristansund: [KSU](http://bolge.vps.webdock.cloud:3000/d/1FHI8WnVz/tides?orgId=1&from=1658440800000&to=1658699999000&var-station_name1=Kristiansund&var-code1=KSU&var-station_name2=Bod%C3%B8&var-code2=BOO&var-inter=1d)    \nHonningsvåg: [HVG](http://bolge.vps.webdock.cloud:3000/d/1FHI8WnVz/tides?orgId=1&from=1665871200000&to=1666475999000&var-station_name1=Honningsv%C3%A5g&var-code1=HVG&var-station_name2=Bod%C3%B8&var-code2=BOO&var-inter=1d)    \nHammerfest: [HFT](http://bolge.vps.webdock.cloud:3000/d/1FHI8WnVz/tides?orgId=1&from=1655111104657&to=1655347583863&var-station_name1=Hammerfest&var-code1=HFT&var-station_name2=Bod%C3%B8&var-code2=BOO&var-inter=1d)  \n2021:  \nHonningsvåg: [HVG](http://bolge.vps.webdock.cloud:3000/d/1FHI8WnVz/tides?orgId=1&var-station_name1=Honningsv%C3%A5g&var-code1=HVG&var-station_name2=Bod%C3%B8&var-code2=BOO&var-inter=1d&from=1632193321081&to=1634042773234)  \nNy-ålesund: [NYA](http://bolge.vps.webdock.cloud:3000/d/1FHI8WnVz/tides?orgId=1&var-station_name1=Ny-%C3%A5lesund&var-code1=NYA&var-station_name2=Bod%C3%B8&var-code2=BOO&var-inter=1d&from=1631931802433&to=1632365595286)  \nTrondhein: [TRD](http://bolge.vps.webdock.cloud:3000/d/1FHI8WnVz/tides?orgId=1&var-station_name1=Trondheim&var-code1=TRD&var-station_name2=Bod%C3%B8&var-code2=BOO&var-inter=1d&from=1620295228091&to=1620398132576)  \nViker: [VIK](http://bolge.vps.webdock.cloud:3000/d/1FHI8WnVz/tides?orgId=1&var-station_name1=Viker&var-code1=VIK&var-station_name2=Bod%C3%B8&var-code2=BOO&var-inter=1d&from=1625449065488&to=1625652154516)  "
   }
  }
 ]
}